# Generated by Django 3.2.9 on 2021-11-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Open', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Close', models.FloatField()),
                ('Volume', models.FloatField()),
                ('Change', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Kosdaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.IntegerField()),
                ('Market', models.TextField()),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kospi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.IntegerField()),
                ('Market', models.TextField()),
                ('Name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Index1', models.FloatField()),
                ('Index2', models.FloatField()),
                ('Label', models.IntegerField()),
            ],
        ),
    ]
