# Generated by Django 3.2.9 on 2021-11-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_finance_kosdaq_kospi_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='Date',
            field=models.TextField(),
        ),
    ]
