# Generated by Django 3.2.9 on 2021-11-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20211130_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='Index1',
            new_name='DXY',
        ),
        migrations.RenameField(
            model_name='risk',
            old_name='Index2',
            new_name='spread',
        ),
    ]
