# Generated by Django 3.2.9 on 2021-11-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20211130_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='DXY',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='spread',
            field=models.FloatField(),
        ),
    ]
